import fs from 'node:fs';
const source=fs.readFileSync('../Greek News Gnn.html','utf8');
const decode=s=>s.replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(+n)).replace(/&#x([\da-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&nbsp;/g,' ').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
const plain=s=>decode(s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]*>/g,' ')).replace(/\s+/g,' ').trim();
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const posts=[];
for(const block of source.split("<div class='post hentry").slice(1)){
 const m=block.match(/<h3 class='post-title[\s\S]*?<a href='([^']+)'>([\s\S]*?)<\/a>/);
 const b=block.match(/<div class='post-body[^>]*>([\s\S]*?)<div style='clear: both;'><\/div>/);
 if(!m||!b)throw Error('Unrecognized post');
 const id=block.match(/itemprop='postId'/)?block.match(/<meta content='(\d+)' itemprop='postId'/)?.[1]:null;
 const date=m[1].match(/\/(\d{4})\/(\d{2})\//);
 posts.push({id,title:plain(m[2]),url:decode(m[1]),excerpt:plain(b[1]),year:date?.[1]||null,month:date?.[2]||null,datePrecision:'month',completeness:'excerpt',sourceFile:'Greek News Gnn.html'});
}
if(posts.length!==10||new Set(posts.map(x=>x.id)).size!==10)throw Error('Expected ten unique posts');
const videos=[...new Set([...source.matchAll(/youtube\.com\/v\/([\w-]+)/g)].map(x=>x[1]))].map(id=>({id,url:'https://www.youtube.com/watch?v='+id}));
fs.writeFileSync('dist/archive.json',JSON.stringify({recoveredAt:'2026-10-08',source:'Saved Blogger homepage; live source could not be reached in this session',posts,videos},null,2));
const cards=posts.map(p=>`<article data-search="${esc((p.title+' '+p.excerpt).toLocaleLowerCase('el'))}"><div class="meta">ΜΑΪΟΣ 2012 · ΑΡΧΕΙΟ · ΑΠΟΣΠΑΣΜΑ</div><h2>${esc(p.title)}</h2><p>${esc(p.excerpt)}</p><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Αρχική ανάρτηση ↗</a></article>`).join('\n');
fs.writeFileSync('dist/archive.html',`<!doctype html><html lang="el"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GNN | Ιστορικό αρχείο</title><meta name="description" content="Ιστορικό αρχείο GNN: αποσπάσματα αναρτήσεων από τον Μάιο 2012 και παλαιές αναφορές βίντεο."><link rel="stylesheet" href="style.css"></head><body><header><div class="brand"><a href="#">GNN<span>ΕΓΚΥΡΗ ΕΝΗΜΕΡΩΣΗ</span></a><p>Η αλήθεια στην υπηρεσία του πολίτη</p><span class="edition">ΙΣΤΟΡΙΚΟ ΑΡΧΕΙΟ</span></div></header><main><section class="intro"><div class="eyebrow">GREEK NEWS · Η ΙΣΤΟΡΙΑ ΜΑΣ</div><h1>Το αρχείο του GNN</h1><p>Παλιές ειδήσεις, πολιτικά κείμενα και αναφορές από το ιστολόγιο Greek News Gnn.</p><div class="stats"><span><strong>10</strong> αποσπάσματα αναρτήσεων</span><span><strong>4</strong> αναφορές βίντεο</span><span><strong>2012</strong> Μάιος</span></div></section><aside class="notice"><strong>Σχετικά με το αρχείο</strong><p>Το περιεχόμενο διατηρείται ως ιστορικό τεκμήριο και δεν αποτελεί σημερινή ειδησεογραφία. Ανακτήθηκε από αποθηκευμένη αρχική σελίδα: περιλαμβάνει αποσπάσματα, όχι τα πλήρη άρθρα ή ολόκληρο το ιστολόγιο. Η ακριβής ημέρα δημοσίευσης δεν είναι διαθέσιμη. Οι αρχικοί σύνδεσμοι και τα βίντεο ενδέχεται να μην είναι πλέον διαθέσιμα.</p></aside><section class="toolbar"><label for="search">Αναζήτηση στο αρχείο</label><input id="search" type="search" placeholder="Τίτλος ή λέξη στο κείμενο…"><p id="count" aria-live="polite">10 από 10 αναρτήσεις</p></section><section id="posts" class="posts">${cards}</section><p id="empty" hidden>Δεν βρέθηκαν αναρτήσεις. Δοκιμάστε άλλη λέξη.</p><section class="videos"><div class="eyebrow">ΑΠΟ ΤΟ ΠΑΛΙΟ ΙΣΤΟΛΟΓΙΟ</div><h2>Αναφορές βίντεο</h2><p>Στο αποθηκευμένο αρχείο υπάρχουν αναφορές σε ορυκτό πλούτο και συνέντευξη του Σπύρου Δρυμίλη για τις δημοτικές εκλογές του Πειραιά. Οι τίτλοι κάθε βίντεο και η διαθεσιμότητά τους δεν έχουν επαληθευτεί.</p><div class="video-links">${videos.map((v,i)=>`<a href="${v.url}" target="_blank" rel="noopener noreferrer">Βίντεο ${i+1} · YouTube ↗</a>`).join('')}</div></section></main><footer><strong>GNN</strong><p>Πηγή: αποθηκευμένη σελίδα Greek News Gnn · Ανάκτηση: 8 Οκτωβρίου 2026</p><a href="archive.json" download>Λήψη δεδομένων αρχείου (JSON)</a></footer><script src="archive.js"></script></body></html>`);
console.log(JSON.stringify({posts:posts.length,videos:videos.length,allExcerptsPresent:posts.every(p=>p.excerpt&&p.title&&p.url),dates: [...new Set(posts.map(p=>p.year+'-'+p.month))]}));
