import fs from 'node:fs';
import path from 'node:path';
import {headlines} from './dist/feed-utils.mjs';
const root='dist', origin='https://gnn-archive.gardenoasis2.chatgpt.site';
const categories=['Επικαιρότητα','Πολιτική','Πολιτική ανάλυση','Κοινωνικά','Οικονομικά','Αθλητικά','Ιστορικά','Θρησκευτικές απόψεις','Ελληνικό Αιγαίο'];
const slugs=['epikairotita','politiki','politiki-analysi','koinonika','oikonomika','athlitika','istorika','thriskeftikes-apopseis','elliniko-aigaio'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const write=(p,s)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s);};
const editions=fs.readdirSync('content/editions').filter(f=>/^\d{4}-\d{2}-\d{2}\.json$/.test(f)).sort().reverse().map(f=>JSON.parse(fs.readFileSync('content/editions/'+f,'utf8')));
if(!editions.length)throw Error('No editions');
const latest=editions[0];
const all=editions.flatMap(e=>e.articles.map(a=>({...a,date:e.date,label:e.label,cutoff:e.cutoff,url:`/articles/${e.date}/${a.slug}.html`})));
const current=all.filter(a=>a.date===latest.date);
const keys=new Set();
for(const e of editions){if(e.articles.length<4||e.articles.length>5)throw Error('Each edition must have 4–5 articles');if(e.cutoff.slice(0,10)!==e.date)throw Error('Edition cutoff mismatch');}
for(const a of all){if(keys.has(a.url))throw Error('Duplicate article URL');keys.add(a.url);if(!categories.includes(a.category)||!a.sources.length||!a.facts.length||!a.analysis.length||!fs.existsSync(path.join(root,a.image)))throw Error('Incomplete article: '+a.slug);for(const s of a.sources){if(!s.url.startsWith('https://')||!s.date)throw Error('Invalid source');}}
const catURL=c=>'/categories/'+slugs[categories.indexOf(c)]+'.html';
const header=(active='')=>`<a class="skip" href="#main">Μετάβαση στο περιεχόμενο</a><div class="topbar"><div class="container top-inner"><span>GREEK NEWS NETWORK</span><span data-current-date aria-label="Σημερινή ημερομηνία Ελλάδας">${esc(latest.label)}</span><a href="/editions.html">Ημερήσιες εκδόσεις</a><a href="/rss.xml">RSS ↗</a></div></div><header class="masthead"><div class="container mast-inner"><a class="logo" href="/" aria-label="GNN αρχική">GNN<span>ΕΓΚΥΡΗ ΕΝΗΜΕΡΩΣΗ</span></a><p class="motto">Η αλήθεια<br>στην υπηρεσία<br>του πολίτη</p><div class="parliament" aria-hidden="true"></div><a class="editor" href="/about.html"><img src="/assets/editor.png" alt="Πορτρέτο Σπυρίδωνος Δρυμιλή"><span>Επιμέλεια:<br><strong>Σπυρίδων Δρυμιλής</strong></span></a></div></header><nav class="navigation" aria-label="Κύρια πλοήγηση"><div class="container nav-inner"><a class="home-link ${active==='home'?'active':''}" href="/" aria-label="Αρχική">⌂</a>${categories.filter(c=>c!=='Επικαιρότητα').map(c=>`<a ${active===c?'aria-current="page" class="active"':''} href="${catURL(c)}">${esc(c)}</a>`).join('')}<a class="archive-link ${active==='archive'?'active':''}" aria-current="${active==='archive'?'page':'false'}" href="/archive.html">Αρχείο</a></div></nav>`;
const footer=()=>`<footer><div class="container footer-inner"><a class="footer-brand" href="/">GNN</a><p>Ειδησεογραφία και ανάλυση υπό την επιμέλεια του Σπυρίδωνα Δρυμιλή</p><div><a href="/about.html">Ταυτότητα & εκδοτική προσέγγιση</a><a href="/editions.html">Όλες οι εκδόσεις</a><a href="/archive.html">Ιστορικό αρχείο</a><a href="/rss.xml">RSS ειδήσεων</a></div></div><div class="container footer-bottom">© ${latest.date.slice(0,4)} GNN</div></footer>`;
function page(title,description,body,url='/',active='',image='/assets/2026-10-08/diplomacy-realistic-v2.png',schema=null){return `<!doctype html><html lang="el"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | GNN</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${origin+url}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="${schema?'article':'website'}"><meta property="og:url" content="${origin+url}"><meta property="og:image" content="${origin+image}"><meta name="twitter:card" content="summary_large_image"><link rel="alternate" type="application/rss+xml" title="GNN καθημερινή έκδοση" href="/rss.xml"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/news.css">${schema?'<script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,'\\u003c')+'</script>':''}</head><body>${header(active)}${body}${footer()}<script src="/news.js" defer></script><script src="/current-date.mjs" type="module"></script></body></html>`;}
const figure=(a,lead=false)=>`<figure class="news-figure"><img ${lead?'fetchpriority="high"':'loading="lazy"'} src="/${esc(a.image)}" alt="${esc(a.imageAlt)}" width="1672" height="941"><figcaption>Εικόνα αρχείου / Editorial εικονογράφηση</figcaption></figure>`;
const card=(a,lead=false)=>`<article class="story ${lead?'lead':''}" data-story data-search="${esc([a.title,a.summary,...a.facts,...a.analysis,a.category,...a.tags].join(' '))}"><a class="picture-link" href="${a.url}" tabindex="-1" aria-hidden="true">${figure(a,lead)}</a><div class="story-copy"><a class="eyebrow" href="${catURL(a.category)}">${esc(a.category)}</a><h${lead?'1':'2'}><a href="${a.url}">${esc(a.title)}</a></h${lead?'1':'2'}><p>${esc(a.summary)}</p><div class="story-meta">${esc(a.date.split('-').reverse().join('.'))} <span>·</span> GNN / Σύνθεση & ανάλυση</div></div></article>`;
const feedSnapshot=JSON.parse(fs.readFileSync('dist/feed-snapshot.json','utf8'));
const feedTime=s=>new Intl.DateTimeFormat('el-GR',{timeZone:'Europe/Athens',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(s));
const externalFeed=()=>`<section id="external-feed" class="external-feed"><span class="eyebrow">ΑΠΟ ΑΛΛΕΣ ΠΗΓΕΣ</span><h2>Ροή ειδήσεων</h2><p class="feed-description">Αυτόματη ροή από Olympia.gr και Onsports.gr. Οι τίτλοι ανοίγουν στην αρχική πηγή.</p><div class="feed-items">${headlines(feedSnapshot.feeds).map(i=>`<a href="${esc(i.url)}" target="_blank" rel="noopener noreferrer"><strong>${esc(i.title)}</strong><small>${esc(i.source)}${i.publishedAt?' · '+feedTime(i.publishedAt):''}</small></a>`).join('')}</div><p class="feed-status" role="status">Αποθηκευμένη ροή: ${feedTime(feedSnapshot.savedAt)} · Ώρα Ελλάδας</p><p class="feed-credit">Έλεγχος ανά 15 λεπτά · <a href="/about.html#external-sources">Πληροφορίες ροής</a></p></section><script id="feed-snapshot" type="application/json">${JSON.stringify(feedSnapshot).replace(/</g,'\u003c')}</script><script src="/feeds.mjs" type="module"></script>`;
const editorial=e=>e.editorial?`<section class="editorial-box" aria-label="Άποψη της έκδοσης"><span class="eyebrow">ΑΠΟΨΗ / EDITORIAL</span><h2>${esc(e.editorial.title)}</h2><blockquote>${esc(e.editorial.text)}</blockquote></section>`:'';
const sidebar=(e,articles,showFeed=false)=>`<aside class="side-column"><section class="day-agenda"><h2>Στο επίκεντρο</h2>${articles.map((a,i)=>`<a href="${a.url}"><span>0${i+1}</span><div><small>${esc(a.category)}</small><h3>${esc(a.title)}</h3></div></a>`).join('')}</section>${showFeed?externalFeed():''}<a class="archive-promo" href="/archive.html"><small>ΑΠΟ ΤΟ 2012</small><h2>Η ιστορία μας,<br>στο αρχείο.</h2><p>10 παλαιά αποσπάσματα και 4 αναφορές βίντεο.</p><span>Εξερευνήστε το αρχείο →</span></a></aside>`;
const issueHeader=e=>`<div class="edition-heading"><div><span class="eyebrow">ΕΚΔΟΣΗ GNN · ${e.articles.length} ΘΕΜΑΤΑ</span><h2>${esc(e.label)}</h2></div></div>`;
const homepageBody=(e,articles,showFeed=false)=>`<main id="main" class="container main-home">${issueHeader(e)}<div class="edition-intro"><span>Η ΣΗΜΕΡΙΝΗ ΜΑΤΙΑ</span><p>Σε έναν κόσμο υπερπληροφόρησης και επιλεκτικής σιωπής, το GNN στέκεται στην πρώτη γραμμή για όλα όσα καθορίζουν το μέλλον της πατρίδας μας.</p></div>${editorial(e)}<div class="front-grid"><div class="main-column">${card(articles[0],true)}<div class="section-heading"><h2>Τα θέματα της έκδοσης</h2><a href="/editions.html">Όλες οι εκδόσεις →</a></div><div class="story-grid">${articles.slice(1).map(a=>card(a)).join('')}</div></div>${sidebar(e,articles,showFeed)}</div><section class="search-section"><div><span class="eyebrow">ΑΝΑΖΗΤΗΣΗ</span><h2>Βρείτε το θέμα που σας ενδιαφέρει</h2></div><div><label for="news-search">Αναζήτηση στα θέματα αυτής της έκδοσης</label><input id="news-search" type="search" placeholder="Λέξη ή θέμα…"><p id="search-count" aria-live="polite"></p></div></section><p id="search-empty" hidden>Δεν βρέθηκαν άρθρα για αυτή την αναζήτηση.</p></main>`;
write('index.html',page('Ημερήσια ενημέρωση με συντηρητική ματιά','Πέντε θέματα της ημέρας, πρωτότυπη ελληνική σύνθεση, πηγές και διακριτή συντηρητική ανάλυση.',homepageBody(latest,current,true),'/','home'));
for(const e of editions){const articles=all.filter(a=>a.date===e.date);write(`editions/${e.date}.html`,page('Έκδοση '+e.label,'Η ημερήσια έκδοση GNN της '+e.label,homepageBody(e,articles),`/editions/${e.date}.html`));}
for(const a of all){const paragraphs=xs=>xs.map(p=>'<p>'+esc(p)+'</p>').join('');const related=all.filter(x=>x.date===a.date&&x.url!==a.url).slice(0,3);const body=`<main id="main" class="container article-main"><div class="breadcrumbs"><a href="/">Αρχική</a> / <a href="${catURL(a.category)}">${esc(a.category)}</a> / ${esc(a.date)}</div><div class="article-top"><a class="eyebrow" href="${catURL(a.category)}">${esc(a.category)}</a><h1>${esc(a.title)}</h1><p class="standfirst">${esc(a.summary)}</p><div class="article-meta"><span>GNN · Πρωτότυπη σύνθεση με AI</span><time datetime="${a.cutoff}">${esc(a.label)}</time><span>${Math.max(2,Math.ceil([...a.facts,...a.analysis].join(' ').split(/\s+/).length/180))}′ ανάγνωση</span><button id="share-article" type="button">Αντιγραφή συνδέσμου ↗</button><span id="share-status" aria-live="polite"></span></div></div>${figure(a,true)}<div class="article-layout"><div class="article-body"><section><div class="section-label">ΤΑ ΓΕΓΟΝΟΤΑ</div>${paragraphs(a.facts)}</section><section class="analysis-section"><div class="section-label">Η ΑΝΑΛΥΣΗ ΤΟΥ GNN</div>${paragraphs(a.analysis)}</section><aside class="watch"><strong>Τι παρακολουθούμε</strong><p>${esc(a.watch)}</p></aside><section class="sources"><h2>Πηγές & τεκμηρίωση</h2><p>Έλεγχος πηγών για την έκδοση της ${esc(a.date.split('-').reverse().join('.'))}. Η ανάλυση αποτυπώνει την εκδοτική θέση του GNN.</p><ol>${a.sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.name)} ↗</a><small>Δημοσίευση πηγής: ${esc(s.date)}</small></li>`).join('')}</ol></section></div><aside class="article-aside"><span class="eyebrow">ΣΤΗΝ ΙΔΙΑ ΕΚΔΟΣΗ</span>${related.map(x=>`<a href="${x.url}"><small>${esc(x.category)}</small><h3>${esc(x.title)}</h3></a>`).join('')}<a href="/editions/${a.date}.html">Ολόκληρη η έκδοση →</a></aside></div></main>`;write(a.url.slice(1),page(a.title,a.summary,body,a.url,a.category,'/'+a.image,{'@context':'https://schema.org','@type':'NewsArticle',headline:a.title,description:a.summary,datePublished:a.cutoff,dateModified:a.cutoff,image:origin+'/'+a.image,author:{'@type':'Organization',name:'GNN'},publisher:{'@type':'Organization',name:'GNN'},inLanguage:'el',mainEntityOfPage:origin+a.url}));}
for(const c of categories){const matches=all.filter(a=>a.category===c||a.tags.includes(c));write(catURL(c).slice(1),page(c,`Άρθρα και ανάλυση GNN στην κατηγορία ${c}.`,`<main id="main" class="container listing-main"><div class="eyebrow">ΘΕΜΑΤΙΚΗ ΕΝΟΤΗΤΑ</div><h1>${esc(c)}</h1><p class="listing-description">${matches.length?matches.length+' άρθρα από τις ημερήσιες εκδόσεις μας.':'Δεν έχει δημοσιευτεί ακόμη άρθρο σε αυτή την ενότητα. Οι ημερήσιες εκδόσεις καλύπτουν τα θέματα που προκύπτουν από την επικαιρότητα.'}</p><div class="category-grid">${matches.map(a=>card(a)).join('')}</div>${!matches.length?'<a class="button-link" href="/">Δείτε την τελευταία έκδοση →</a>':''}</main>`,catURL(c),c));}
write('editions.html',page('Ημερήσιες εκδόσεις','Όλες οι ημερήσιες εκδόσεις GNN, με μόνιμες ημερομηνίες.',`<main id="main" class="container listing-main"><span class="eyebrow">ΤΟ ΑΡΧΕΙΟ ΤΩΝ ΝΕΩΝ ΕΚΔΟΣΕΩΝ</span><h1>Κάθε μέρα, μια νέα ματιά.</h1><div class="edition-list">${editions.map(e=>`<a href="/editions/${e.date}.html"><span>${esc(e.label)}</span><strong>${e.articles.length} άρθρα →</strong></a>`).join('')}</div><a href="/archive.html">Αναζητάτε το παλιό ιστολόγιο; Ιστορικό αρχείο GNN →</a></main>`,'/editions.html'));
write('about.html',page('Ταυτότητα & εκδοτική προσέγγιση','Η συντηρητική εκδοτική προσέγγιση του GNN και η χρήση της τεχνητής νοημοσύνης.',`<main id="main" class="container about-main"><span class="eyebrow">GREEK NEWS NETWORK</span><h1>Η αλήθεια στην υπηρεσία του πολίτη.</h1><p class="standfirst">Μια καθημερινή ελληνική έκδοση με συντηρητική οπτική, ανοιχτές πηγές και καθαρή διάκριση είδησης και σχολιασμού.</p><div class="about-body"><h2>Η εκδοτική μας θέση</h2><p>Εθνική κυριαρχία και ασφάλεια. Θεσμοί που λειτουργούν και λογοδοτούν. Ελεύθερη, παραγωγική οικονομία. Κοινωνική συνοχή και σεβασμός στην ελληνική πολιτιστική συνέχεια. Αυτές οι αρχές καθοδηγούν τη θεματολογία και την ανάλυσή μας.</p><h2>Πώς γράφονται τα άρθρα</h2><p>Τα νέα άρθρα αποτελούν πρωτότυπη σύνθεση και με τη βοήθεια τεχνητής νοημοσύνης. Βασίζονται σε δημοσιευμένες πηγές, οι οποίες παρατίθενται μέσα σε κάθε άρθρο για λόγους διαφάνειας. Οι ενότητες «Τα γεγονότα» και «Η ανάλυση του GNN» διαχωρίζουν την ενημέρωση από τη θέση της έκδοσης. Η ημερομηνία έκδοσης παραμένει ορατή και οι παλαιές εκδόσεις διατηρούνται.</p><h2>Οι εικόνες</h2><p>Οι εικόνες των άρθρων φέρουν τη σήμανση <em>«Εικόνα αρχείου / Editorial εικονογράφηση»</em>. Για τη δημιουργία, επεξεργασία ή επιλογή τους ενδέχεται να έχει γίνει χρήση εργαλείων Τεχνητής Νοημοσύνης (AI), με αποκλειστικό σκοπό τη συμβολική και αισθητική πλαισίωση της ειδησεογραφίας.</p><h2>Η ιστορία του GNN</h2><p>Το παλιό ιστολόγιο Greek News Gnn και το υλικό με την ταυτότητα του Σπύρου Δρυμίλη αποτελούν τη βάση της παρουσίας μας. Το ιστορικό αρχείο περιλαμβάνει όσα αποσπάσματα ανακτήθηκαν από την αποθηκευμένη σελίδα του 2012.</p><a class="button-link" href="/archive.html">Στο ιστορικό αρχείο →</a><h2 id="external-sources">Η εξωτερική ροή ειδήσεων</h2><p>Στην αρχική σελίδα εμφανίζονται αυτόματα τίτλοι από τα RSS των Olympia.gr και Onsports.gr, με αναφορά στην πηγή και σύνδεσμο προς το αρχικό άρθρο. Πρόκειται για εξωτερική ειδησεογραφία, ξεχωριστή από τη σύνθεση και την ανάλυση του GNN.</p><h2>Διορθώσεις</h2><p>Όταν προκύπτει ουσιαστική διόρθωση, ενημερώνεται το σχετικό άρθρο με σημείωση και νέα ώρα ενημέρωσης. Οι αρχικές ημερομηνίες και οι πηγές παραμένουν διαθέσιμες.</p></div></main>`,'/about.html'));
write('articles.json',JSON.stringify(all,null,2));
write('rss.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>GNN · Ημερήσια έκδοση</title><link>${origin}/</link><description>Ειδήσεις και συντηρητική ανάλυση στα ελληνικά.</description><language>el</language><lastBuildDate>${new Date(latest.cutoff).toUTCString()}</lastBuildDate>${all.map(a=>`<item><title>${esc(a.title)}</title><link>${origin+a.url}</link><guid isPermaLink="true">${origin+a.url}</guid><pubDate>${new Date(a.cutoff).toUTCString()}</pubDate><category>${esc(a.category)}</category><description>${esc(a.summary)}</description></item>`).join('')}</channel></rss>`);
write('favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="8" fill="#051c35"/><text x="32" y="47" text-anchor="middle" font-family="Georgia,serif" font-size="48" fill="#ddb950">G</text></svg>');
const urls=['/','/about.html','/editions.html','/archive.html',...all.map(a=>a.url),...categories.map(catURL),...editions.map(e=>'/editions/'+e.date+'.html')];
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>'<url><loc>'+esc(origin+u)+'</loc></url>').join('')+'</urlset>');
write('robots.txt','User-agent: *\nAllow: /\nSitemap: '+origin+'/sitemap.xml\n');
const archiveData=JSON.parse(fs.readFileSync('dist/archive.json','utf8'));
const archiveCards=archiveData.posts.map(p=>`<article data-search="${esc((p.title+' '+p.excerpt).toLocaleLowerCase('el'))}"><div class="eyebrow">ΜΑΪΟΣ 2012 · ΑΡΧΕΙΟ · ΑΠΟΣΠΑΣΜΑ</div><h2><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.title)}</a></h2><p>${esc(p.excerpt)}</p><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Αρχική ανάρτηση ↗</a></article>`).join('');
const archiveBody=`<main id="main" class="archive-main"><section class="archive-hero"><div class="container"><span class="eyebrow">GREEK NEWS · Η ΙΣΤΟΡΙΑ ΜΑΣ</span><h1>Το αρχείο του GNN</h1><p>Παλιές ειδήσεις, πολιτικά κείμενα και αναφορές από το ιστολόγιο Greek News Gnn.</p><div class="archive-stats"><span><strong>${archiveData.posts.length}</strong> αποσπάσματα αναρτήσεων</span><span><strong>${archiveData.videos.length}</strong> αναφορές βίντεο</span><span><strong>2012</strong> Μάιος</span></div></div></section><div class="container archive-content"><aside class="archive-notice"><h2>Σχετικά με το αρχείο</h2><p>Το περιεχόμενο διατηρείται ως ιστορικό αρχείο και δεν αποτελεί σημερινή ειδησεογραφία. Ανακτήθηκε από το <a href="https://greeknews-gnn.blogspot.com/" target="_blank" rel="noopener noreferrer">https://greeknews-gnn.blogspot.com/</a></p></aside><section class="archive-search"><label for="search">Αναζήτηση στο αρχείο</label><input id="search" type="search" placeholder="Τίτλος ή λέξη στο κείμενο…"><p id="count" aria-live="polite">10 από 10 αναρτήσεις</p></section><section id="posts" class="archive-posts">${archiveCards}</section><p id="empty" hidden>Δεν βρέθηκαν αναρτήσεις. Δοκιμάστε άλλη λέξη.</p><section class="archive-videos"><span class="eyebrow">ΑΠΟ ΤΟ ΠΑΛΙΟ ΙΣΤΟΛΟΓΙΟ</span><h2>Αναφορές βίντεο</h2><p>Παλαιά βίντεο από το ιστολόγιο. Οι τίτλοι και οι προεπισκοπήσεις προέρχονται από το YouTube. Όπου δεν επιστρέφονται πλέον στοιχεία, διατηρείται ο αρχικός σύνδεσμος με σχετική ένδειξη.</p><div>${archiveData.videos.map(v=>`<a class="archive-video-card" href="${esc(v.url)}" target="_blank" rel="noopener noreferrer">${v.thumbnail?`<div class="video-preview"><img src="${esc(v.thumbnail)}" alt="" loading="lazy" width="480" height="360"><span aria-hidden="true">▶</span></div>`:`<div class="video-unavailable" aria-hidden="true">Μη διαθέσιμη προεπισκόπηση</div>`}<h3>${esc(v.title||'Μη διαθέσιμο βίντεο στο YouTube')}</h3><small>${esc(v.author||'Αρχική αναφορά: '+v.id)} · YouTube ↗</small></a>`).join('')}</div></section><p><a href="/archive.json" download>Λήψη δεδομένων αρχείου (JSON)</a></p></div></main><script src="/archive.js" defer></script>`;
write('archive.html',page('Ιστορικό αρχείο','Ιστορικό αρχείο GNN από το ιστολόγιο Greek News Gnn.',archiveBody,'/archive.html','archive','/assets/parliament-history.jpg'));
console.log(JSON.stringify({editions:editions.length,articles:all.length,categories:categories.length,latest:latest.date}));
